### ISSUE TITLE
sphinx_build with 1.7.0

### ISSUE THREAD

**Issue by bnmnetp** [sphinx-contrib/paverutils#1]
Hi Doug,

Have you tried this with Sphinx 1.7.0 ?  My project that uses paverutils just broke when I upgraded.  Works fine on 1.6.3.  The funny thing is the sphinx-build command it emits seems to work ok if I copy it and run it from the shell, but it dies when started up by paver.   Reverting to 1.6.3 is fine.

Here is the error message in case it rings any bells for a place for me to start looking.

```
error: cannot find files [path('./build/thinkcspy')]
```

Thanks,

Brad

**Comment by bnmnetp** [comment]
This seems like a likely culprit:  https://github.com/sphinx-doc/sphinx/pull/3668

**Comment by dhellmann** [comment]
6268e5952fa564cefac05c06823b929a60522613 should fix this.
